language: java
before_script:
  - mkdir -p out
script:
  - java -jar ./bin/yuicompressor-2.4.8.jar -o out/'.css$:-min.css' css/*.css
deploy:
    provider: s3
    bucket: nasu-travis-ci
    region: ap-northeast-1
    endpoint: s3-ap-northeast-1.amazonaws.com
    local-dir: out
    upload-dir: css
    on:
        branch: master
notifications:
    slack: sharpensword-net:xLWS9sGLUjPZIw1bCMxBKdZz
    on_success: always


