language: java
script:
    - java -jar ./bin/yuicompressor-2.4.8.jar -o '.css$:-min.css' css/*.css

deploy:
    provider: s3
    access_key_id: "${access_key_id}"
    secret_access_key: "${secret_access_key}"
    bucket: nasu-travis-ci
    region: ap-northeast-1
    endpoint: s3-ap-northeast-1.amazonaws.com
    skip_cleanup: true
    upload-dir: "${TRAVIS_BUILD_NUMBER}"/css
    on:
        branch: master

notifications:
    slack: sharpensword-net:xLWS9sGLUjPZIw1bCMxBKdZz
    on_success: always


